### PR TITLE
Update shatteredpd.md

### PR DESCRIPTION
**Pull request by fabiopolancoe**
This is a little change, i only added the (Unofficial) snapcraft.io and F-Droid links to the downloads.

### CODE REVIEW

**Comment by 00-Evan** [comment]
I don't intend to link to unofficial distributions of the game.

**Comment by danipozo** [comment]
Hi, is the F-Droid distribution considered unofficial too? I've seen that you've linked to it in the v0.8.2 post.

**Comment by 00-Evan** [comment]
@danipozo F-Droid was previously an officially supported distribution, but I have dropped it due to serious technical problems with their distribution of Shattered updates. You'll note F-Droid STILL does not properly offer 0.8.2, and incorrectly insists Shattered has anti-features. I opened issues to try and get this addressed about a month ago and no progress has been made.

**Comment by danipozo** [comment]
This is sad. Navigating the issues, I don't understand what is the problem. The threads and issues all seem to say that it's a problem with an outdated Gradle version, which should have been resolved by now. Also, other apps seem to be marked as having known security vulnerabilities with no explanation, even though this is not present in the metadata for the builds.

Do you have anymore of a clue of what's going on?

**Comment by 00-Evan** [comment]
Unfortunately I don't. This isn't just due to Gradle versions though (although that's a recurring frustration in and of itself). In addition to the anti-features F-Droid has successfully built versions of Shattered and then just sends them straight to the archive rather than distributing them via the website and app. It seems at this point my only recourse is to stop working on my actual game and try and fix the issue with F-Droid myself via a pull request. Obviously that's not feasible.

**Pull request closed without merging**
